### PR TITLE
Copy edit guide notebooks 00-01

### PR DESCRIPTION
**Pull request by lglattly**
~~Note this is a work in progress to show I'm currently working through the notebooks I was assigned to copy edit.~~

Finished

### CODE REVIEW

**Comment by lglattly** [comment]
notebook 01.05 calibration overview still contains a note to self and seems to be missing a summary line at the end, perhaps it's not finished? I also noticed there are no notebooks 01.01 and 01.02.

**Comment by lglattly** [comment]
I've finished copy editing notebooks 00-01: see previous comments regarding specific notebook questions.

**Comment by mwcraig** [comment]
@lglattly -- I'm *really* sorry for the delay. Apparently I hadn't set up notifications on this repo.

**Comment by mwcraig** [comment]
> I also noticed there are no notebooks 01.01 and 01.02.

Those were in the original outline then subsequently dropped. I'm planning a renumbering once everything is complete.

**Comment by mwcraig** [comment]
> notebook 01.05 calibration overview still contains a note to self and seems to be missing a summary line at the end, perhaps it's not finished? 

Thanks, opening an issue to remind me to fix this.

**Comment by lglattly** [comment]
> Thanks @lglattly this is really helpful! I especially appreciate that you caught all of the "just," "simply" and "straightforward" sort of language. I'd been trying to avoid it but a lot slipped through.
> 
> I've added a spell check notebook extension so hopefully future notebooks will have fewer spelling errors.

Excellent @mwcraig, I'm so glad to hear it was helpful!

**Pull request merged**
